### ISSUE TITLE
pairwiseMedianTest

### ISSUE THREAD

**Issue by desmond-tuiyot** [cran/rcompanion#1]
I was wondering what the purpose of line 85 in the pairwiseMedianTest code is. Seems unnecessary and results in long printouts of the possible pairings of the data. Is it possible to remove it or suppress it?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the authors in the DESCRIPTION file. Thanks!

**Comment by desmond-tuiyot** [comment]
Thank you!
